### ISSUE TITLE
Import of .ics failed

### ISSUE THREAD

**Issue by ghost** [libasys/ownCloud-8.1-Calendar-App#10]
Firstly i created an export of my current calendar, based on ownCloud 8.0.4.
The calendar was exported to 'rieger.ics'
Then i was uploading the export-file to the new ownCloud 8.1 RC1 instance.
When i was trying to import the calendar file a blank import page appears.
![calendar-ics-failed](https://cloud.githubusercontent.com/assets/12971682/8262269/6958ccd4-16d1-11e5-94eb-e6368751fda7.JPG)

**Comment by ghost** [comment]
- ownCloud 8.1 RC1 (https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2) 
- php 5.6.8

Log: {"reqId":"VYR5TlUNmGEAAGuJsv8AAAAB","remoteAddr":"111.222.333.444","app":"PHP","message":"Class 'OC\Cache' not found at \/www\/htdocs\/v00000\/c-rieger.de\/owncloud8\/apps\/calendar\/controller\/importcontroller.php#120","level":3,"time":"2015-06-19T20:19:26+00:00"}
{"reqId":"VYR5TlUNmGEAAGVimHgAAAAI","remoteAddr":"111.222.333.444.","app":"PHP","message":"Class 'OC\Cache' not found at \/www\/htdocs\/v00000\/c-rieger.de\/owncloud8\/apps\/calendar\/lib\/import.php#374","level":3,"time":"2015-06-19T20:19:26+00:00"}

**Comment by libasys** [comment]
thanks for the bug report! this bug is fixed with the next version of the calendar app that i commit!

**Comment by ghost** [comment]
many thx for your response

**Comment by libasys** [comment]
Should be fixed with the new version, added the popover feature, also!
A new calendar year view is also available and some other small new features!

**Comment by Tramour** [comment]
Encountered the same problem... Export from 8.0.4 from a couple of calendars. Import was possible for all but one calendar. This one was the lagest and it did not work (Import fehlgeschlagen). I used your latest version from today.

**Comment by libasys** [comment]
How many entries have the largest calendar import (round about)?

**Comment by ghost** [comment]
My personal calendar contains about 1073 Events.
I just recognized that the Name of the calendar consists of german "Umlaute" so the exported calendar was stored as "PersÃ¶nlich.ics" instead of "Persönlich.ics". Maybe this is also related?
Renaming the file to "persoenlich.ics" and editing (replacing inside) the file did not solve that issue.

**Comment by libasys** [comment]
could be a problem, have you tried the new version of the calendar app and import the ics file?

**Comment by ghost** [comment]
not yet, i will do it within the next 3 hours

**Comment by ghost** [comment]
Yes, works fine. the Import succeeded for all the 1073 events!
The only Issue: no Progress state/bar appeared during the import, just the imprt message at the end appeared after few seconds.

![cal01](https://cloud.githubusercontent.com/assets/12971682/8324531/c74af654-1a51-11e5-8641-24eee435bc45.PNG)
![cal02](https://cloud.githubusercontent.com/assets/12971682/8324529/c7384414-1a51-11e5-9fd3-432f32ef5020.PNG)
![cal03](https://cloud.githubusercontent.com/assets/12971682/8324530/c73abc30-1a51-11e5-99e4-af9de3160cc3.PNG)
Many thanks, great Job! I will spend more time for testing this week and will give you a Feedback.

**Comment by libasys** [comment]
perferct! merci!

**Comment by ghost** [comment]
Unfortunately the view "YEAR" remains blank, all other views are shown as expected.
And in addition the two gray buttons beside YEAR are not named or titled.
![cal04](https://cloud.githubusercontent.com/assets/12971682/8324684/2fe3e882-1a53-11e5-83ee-807ba560a1bf.PNG)

**Comment by libasys** [comment]
Have you cleared your browser cache?

**Comment by ghost** [comment]
yes i did. neither in IE11 nor in firefox 38.0.5 the year-calendar or title entries appear.
no logentries in the owncloud.log

**Comment by libasys** [comment]
Your error console of your browser, some js errors?

**Comment by ghost** [comment]
09:46:44.112 TypeError: fcViews[newViewName] is not a constructor1 fullcalendar.js:361:16

**Comment by libasys** [comment]
Please test, deactivate the calendar with the 1073 entries, and than test it again! Or have you a demo account for me, so i can debug it self?

**Comment by ghost** [comment]
Disabling does not lead to any changes 
your login:
https://www.c-rieger.de/owncloud8
libasys
libasys

**Comment by libasys** [comment]
ok thanks, i see what happend. Please update your installation of the calendar app! No data get lost.
Delete the old folder "calendar" in your app directory and than upload the new calendar version in your apps directory! Something went wrong if you uploaded the new version of the calendar app to your app directory! The best way imho is to delete the old folder and than upload the new folder (calendar version). Sometimes ftp progams not update all files if you copy some new files into existing files!

**Comment by ghost** [comment]
this version ?
ownCloud-8.1-Calendar-App-master.zip
last updated 23.06. / 19:07?

**Comment by libasys** [comment]
yes

**Comment by criegerde** [comment]
hhmmm...same behaviour
![cal01](https://cloud.githubusercontent.com/assets/12971682/8325879/23ff6c80-1a5d-11e5-8e55-9cef1aadb682.PNG)
![cal02](https://cloud.githubusercontent.com/assets/12971682/8325881/24009eb6-1a5d-11e5-8f76-19bc9f4d5e8f.PNG)
![cal03](https://cloud.githubusercontent.com/assets/12971682/8325880/23ff6fc8-1a5d-11e5-8e9c-e41badd4a627.PNG)
![cal04](https://cloud.githubusercontent.com/assets/12971682/8325882/240406b4-1a5d-11e5-8ea6-cadc098086d9.PNG)
![05](https://cloud.githubusercontent.com/assets/12971682/8325907/51452ea0-1a5d-11e5-82d1-bbb6ccf4f144.PNG)

**Comment by ghost** [comment]
same behaviour
![01](https://cloud.githubusercontent.com/assets/12971682/8325918/6400a38a-1a5d-11e5-9521-90b3498c737e.PNG)
![02](https://cloud.githubusercontent.com/assets/12971682/8325919/64034f40-1a5d-11e5-9c37-510c66f3d74a.PNG)
![03](https://cloud.githubusercontent.com/assets/12971682/8325920/6403cf56-1a5d-11e5-9558-49610dad716d.PNG)
![04](https://cloud.githubusercontent.com/assets/12971682/8325917/63f37b06-1a5d-11e5-8bbd-1bc5878e2950.PNG)
![05](https://cloud.githubusercontent.com/assets/12971682/8325921/640556be-1a5d-11e5-884f-9af8a6c11b13.PNG)

**Comment by ghost** [comment]
10:37:58.710 TypeError: fcViews[newViewName] is not a constructor1 fullcalendar.js:361:16

**Comment by ghost** [comment]
![06](https://cloud.githubusercontent.com/assets/12971682/8326018/51ba9be4-1a5e-11e5-8fe4-b60198341bfd.PNG)

**Comment by libasys** [comment]
have you extract the zip file and uploaded only the folder "calendar" in your apps directory? You are using a older version of the calendar

**Comment by ghost** [comment]
strange, that is exactly what i did.
extract -> compress calendar-folder -> upload/extract  new calendar.zip

**Comment by libasys** [comment]
Have a look to your files structure of your app directory!
The correct structure is
apps/calendar

**Comment by ghost** [comment]
i put the uploaded zip in your account, mentioned above

**Comment by ghost** [comment]
yes
![07](https://cloud.githubusercontent.com/assets/12971682/8326150/4e0406d8-1a5f-11e5-9904-cc212485273f.PNG)

**Comment by libasys** [comment]
yes that is the correct version, have you activated some cache functions in your config or otherwise?

**Comment by ghost** [comment]
no. i didn't. Maybe my provider did (all-inkl.com)?
i mapped the calendar-folder as external storage in your account.
just if you would investigate further in this?!

**Comment by libasys** [comment]
something strange by your installation
your path in the header of calendar js files are:

```
<script src="/owncloud8/calendar/js/3rdparty/fullcalendar.js?v=bade8964df463f882e482d91ba75c079"></script>
```

but correct path should be:

```
<script src="/owncloud8/apps/calendar/js/3rdparty/fullcalendar.js?v=bade8964df463f882e482d91ba75c079"></script>
```

you see in the path above "apps" is missing, so it loads a calendar version from another place!
I think some caching mechanism is working on your server?!

**Comment by libasys** [comment]
is this value in your config/config.php enabled or disabled?

```
'asset-pipeline.enabled' => false
```

**Comment by ghost** [comment]
not set (<- neither true nor false)

**Comment by libasys** [comment]
ok! go to your apps and deactivate the calendar app hit F5 for refresh and than activate it again!

**Comment by ghost** [comment]
ok, i disabled the app and hit F5. the app was disabled and disappeared from the enabled apps
the app appeared in the area "not activated apps", i pressed F5 again and enabled the the calendar
i pressed F5 again.
... once again - same errors occur

**Comment by libasys** [comment]
What is your server environment? apache, mysql etc

**Comment by ghost** [comment]
PHP 5.6.8 as AddHandler (AddHandler php56-cgi .php)
<= http://dd35328.kasserver.com/infophp.php56

(Serverseitig: http://dd35328.kasserver.com/infophp.php -> PHP Version 5.4.40-nmm1)
MySQL 5.6.24
Apache2

**Comment by libasys** [comment]
It is a problem of caching, the js and css files get cached from server side! the interesting here is, if you add a new js/css file to calendar like with the new version of calendar app (jquery.webui-popover.js/.css) Here comes the correct path, but all other before get the wrong path without "apps" in the path!

**Comment by ghost** [comment]
should we wait for a specific time (for example one day?) or should i get in contact with all-inkl.com-support and ask them for caching-specifics?

**Comment by Tramour** [comment]
@criegerde  I'd be very interested in your results with all inkl. Seems we have the same testing enviroment.

**Comment by libasys** [comment]
please look into your admin settings page if memcache is active or if you receive an error message on
"Sicherheits- & Einrichtungswarnungen"

**Comment by ghost** [comment]
yes, a warning is shown:
"Es wurde kein PHP Memory Cache konfiguriert. Konfiguriere zur Erhöhung der Leistungsfähigkeit, soweit verfügbar, einen Memory Cache. Weitere Informationen finden Sie in unserer Dokumentation."
But this could not be solved. it would only be possible using Managed Server hosted by all-inkl.com

**Comment by ghost** [comment]
I sent an email-request  to all-inkl.com:

**Comment by libasys** [comment]
if i look at the source code of your oc install i see this strange behaviour:

```
<link rel="stylesheet" href="/owncloud8/apps/calendar/css/3rdparty/jquery.webui-popover.css?v=bade8964df463f882e482d91ba75c079" media="screen">
<link rel="stylesheet" href="/owncloud8/calendar/css/style.css?v=bade8964df463f882e482d91ba75c079" media="screen">
```

the first path is correct the second is not! Did you understand the problem?

**Comment by ghost** [comment]
Support sagt:
Hallo herr Rieger,
vielen Dank für Ihre Anfrage.
Das kann hier nicht die Ursache sein da wir serverseitig kein Caching einsetzen.
Bei weiteren Fragen...

**Comment by libasys** [comment]
ok last test! please download now the version of the calendar app and install this to your apps directory! I have only changed the version number in the appinfo/info.xml file, but with this little change the update procedure starts and you get a new version string for your js/css files! Perhaps this can solve the problem!

**Comment by ghost** [comment]
i will do but with a delay of 2 hours...meeting. Sorry and Thanks

**Comment by libasys** [comment]
ok

**Comment by Tramour** [comment]
@libasys Worked for me. Import was possible.

**Comment by libasys** [comment]
Thanks for the feedback ;)

**Comment by ghost** [comment]
what have i done?
i installed ownCloud 8.1RC1 again from scratch
i uploaded the calendar.app v. 1.0.2
![cal102a](https://cloud.githubusercontent.com/assets/12971682/8332113/638d5e6e-1a8c-11e5-94f9-dcfea955ffca.PNG)
Import of *.ics succeeded
...
BUT
...
No view year anymore?!
![cal102](https://cloud.githubusercontent.com/assets/12971682/8332040/f1cec718-1a8b-11e5-85c8-59fdc2e90d31.PNG)
Works as designed or a new issue?

**Comment by Tramour** [comment]
Have you checked on settings (upper right corner), active views?

**Comment by ghost** [comment]
No, i didn't, sorry!

Now it works fine, the import and as well all calendar-views!
Many thx for your assistance.
From my opinion the issue can be closed.

**Comment by ghost** [comment]
Timezone was automatically set to Europe/Berlin. 
your account (libasys) may remain open for test putposes, are you intersted in?
if yes, please change your pwd.

**Comment by libasys** [comment]
changed password!

**Comment by ggeorgg** [comment]
I have a problem with importing my .ics file into my new owncloud installation 8.1. 
The progress bar is standing still when I open my .ics file. when I look into the app, I see a new calendar, but without any events. 
The error shown in the log is:
Class 'OC\Cache' not found at /www/htdocs/....../....../apps/calendar/lib/import.php#330
I also replaced the all the calendar files in the folder apps/calendar/ with the latest calendar-master branch on git, just to try it. The error stays the same. 
A second problem is, that I can't see in the owncloud backend, that I changed the calendar app. It still says version 0.7.1. What am I doing wrong?

**Comment by libasys** [comment]
Hi @ggeorgg, the calendar+ repo has moved to https://github.com/libasys/calendarplus! that is the acutal repo for calendarplus! Or you can download it on the appstore: https://apps.owncloud.com/content/show.php/Calendar+Plus?content=170560! Please work with the new version of calendar+ than also the import should work! the folder of calendar+ named "calendarplus".

**Comment by ggeorgg** [comment]
great! it works now.
but I still have a question: How should I name the folder on the webspace in which the new calender app is located? /apps/calendarplus or /apps/calendar. Does is make any difference?
edit: sorry, just saw, that you it is already written here: https://github.com/libasys/calendarplus
-> foldername: calendarplus
Thank you very much for your help!
